export enum TournamentActions {
  FETCH_ALL_TOURNAMENT_START,
  FETCH_ALL_TOURNAMENT_SUCCESS,
  FETCH_ALL_TOURNAMENT_ERROR,
  SEARCH_TOURNAMENT,
  CREATE_TOURNAMENT,
  EDIT_TOURNAMENT,
  DELETE_TOURNAMENT
}
